version: '3.7'
services:

  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"
       
  app:
    container_name: price-checker-api
    init: true
    build: .
    ports:
      - "9000:9000"
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - PORT=9000
    depends_on: 
      - "mongo"

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
       - "27018:27017"

